// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: single_sint32.proto

#ifndef PROTOBUF_INCLUDED_single_5fsint32_2eproto
#define PROTOBUF_INCLUDED_single_5fsint32_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_single_5fsint32_2eproto 

namespace protobuf_single_5fsint32_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_single_5fsint32_2eproto
class Example1;
class Example1DefaultTypeInternal;
extern Example1DefaultTypeInternal _Example1_default_instance_;
class Example2;
class Example2DefaultTypeInternal;
extern Example2DefaultTypeInternal _Example2_default_instance_;
namespace google {
namespace protobuf {
template<> ::Example1* Arena::CreateMaybeMessage<::Example1>(Arena*);
template<> ::Example2* Arena::CreateMaybeMessage<::Example2>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class Example1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Example1) */ {
 public:
  Example1();
  virtual ~Example1();

  Example1(const Example1& from);

  inline Example1& operator=(const Example1& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Example1(Example1&& from) noexcept
    : Example1() {
    *this = ::std::move(from);
  }

  inline Example1& operator=(Example1&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Example1& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Example1* internal_default_instance() {
    return reinterpret_cast<const Example1*>(
               &_Example1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Example1* other);
  friend void swap(Example1& a, Example1& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Example1* New() const final {
    return CreateMaybeMessage<Example1>(NULL);
  }

  Example1* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Example1>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Example1& from);
  void MergeFrom(const Example1& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Example1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // sint32 sint32Val = 1;
  void clear_sint32val();
  static const int kSint32ValFieldNumber = 1;
  ::google::protobuf::int32 sint32val() const;
  void set_sint32val(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Example1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 sint32val_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_single_5fsint32_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Example2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Example2) */ {
 public:
  Example2();
  virtual ~Example2();

  Example2(const Example2& from);

  inline Example2& operator=(const Example2& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Example2(Example2&& from) noexcept
    : Example2() {
    *this = ::std::move(from);
  }

  inline Example2& operator=(Example2&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Example2& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Example2* internal_default_instance() {
    return reinterpret_cast<const Example2*>(
               &_Example2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Example2* other);
  friend void swap(Example2& a, Example2& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Example2* New() const final {
    return CreateMaybeMessage<Example2>(NULL);
  }

  Example2* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Example2>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Example2& from);
  void MergeFrom(const Example2& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Example2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated sint32 sint32Val = 1;
  int sint32val_size() const;
  void clear_sint32val();
  static const int kSint32ValFieldNumber = 1;
  ::google::protobuf::int32 sint32val(int index) const;
  void set_sint32val(int index, ::google::protobuf::int32 value);
  void add_sint32val(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      sint32val() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_sint32val();

  // @@protoc_insertion_point(class_scope:Example2)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > sint32val_;
  mutable int _sint32val_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_single_5fsint32_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Example1

// sint32 sint32Val = 1;
inline void Example1::clear_sint32val() {
  sint32val_ = 0;
}
inline ::google::protobuf::int32 Example1::sint32val() const {
  // @@protoc_insertion_point(field_get:Example1.sint32Val)
  return sint32val_;
}
inline void Example1::set_sint32val(::google::protobuf::int32 value) {
  
  sint32val_ = value;
  // @@protoc_insertion_point(field_set:Example1.sint32Val)
}

// -------------------------------------------------------------------

// Example2

// repeated sint32 sint32Val = 1;
inline int Example2::sint32val_size() const {
  return sint32val_.size();
}
inline void Example2::clear_sint32val() {
  sint32val_.Clear();
}
inline ::google::protobuf::int32 Example2::sint32val(int index) const {
  // @@protoc_insertion_point(field_get:Example2.sint32Val)
  return sint32val_.Get(index);
}
inline void Example2::set_sint32val(int index, ::google::protobuf::int32 value) {
  sint32val_.Set(index, value);
  // @@protoc_insertion_point(field_set:Example2.sint32Val)
}
inline void Example2::add_sint32val(::google::protobuf::int32 value) {
  sint32val_.Add(value);
  // @@protoc_insertion_point(field_add:Example2.sint32Val)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Example2::sint32val() const {
  // @@protoc_insertion_point(field_list:Example2.sint32Val)
  return sint32val_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Example2::mutable_sint32val() {
  // @@protoc_insertion_point(field_mutable_list:Example2.sint32Val)
  return &sint32val_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_single_5fsint32_2eproto
