// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: single_length_delimited_all.proto

#include "single_length_delimited_all.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_single_5flength_5fdelimited_5fall_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_single_5flength_5fdelimited_5fall_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Example1_EmbeddedMessage;
}  // namespace protobuf_single_5flength_5fdelimited_5fall_2eproto
class Example1_EmbeddedMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Example1_EmbeddedMessage>
      _instance;
} _Example1_EmbeddedMessage_default_instance_;
class Example1DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Example1>
      _instance;
} _Example1_default_instance_;
namespace protobuf_single_5flength_5fdelimited_5fall_2eproto {
static void InitDefaultsExample1_EmbeddedMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Example1_EmbeddedMessage_default_instance_;
    new (ptr) ::Example1_EmbeddedMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Example1_EmbeddedMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Example1_EmbeddedMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsExample1_EmbeddedMessage}, {}};

static void InitDefaultsExample1() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Example1_default_instance_;
    new (ptr) ::Example1();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Example1::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Example1 =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsExample1}, {
      &protobuf_single_5flength_5fdelimited_5fall_2eproto::scc_info_Example1_EmbeddedMessage.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Example1_EmbeddedMessage.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Example1.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Example1_EmbeddedMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Example1_EmbeddedMessage, int32val_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Example1_EmbeddedMessage, stringval_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Example1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Example1, stringval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Example1, bytesval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Example1, embeddedexample1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Example1, repeatedint32val_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Example1, repeatedstringval_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Example1_EmbeddedMessage)},
  { 7, -1, sizeof(::Example1)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Example1_EmbeddedMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Example1_default_instance_),
};

static void protobuf_AssignDescriptors() {
  AddDescriptors();

  // 为每个 descriptor 分配空间，设置 metadata_ 对象
  AssignDescriptors(
      "single_length_delimited_all.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

static void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

static void AddDescriptorsImpl() {
  // 添加元信息
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n!single_length_delimited_all.proto\"\321\001\n\010"
      "Example1\022\021\n\tstringVal\030\001 \001(\t\022\020\n\010bytesVal\030"
      "\002 \001(\014\0223\n\020embeddedExample1\030\003 \001(\0132\031.Exampl"
      "e1.EmbeddedMessage\022\030\n\020repeatedInt32Val\030\004"
      " \003(\005\022\031\n\021repeatedStringVal\030\005 \003(\t\0326\n\017Embed"
      "dedMessage\022\020\n\010int32Val\030\001 \001(\005\022\021\n\tstringVa"
      "l\030\002 \001(\tb\006proto3"
  };
  // 将元信息 descriptor 内容注册到池子里
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 255);
  // 注册所有 message 到 MessageFactory
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "single_length_delimited_all.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_single_5flength_5fdelimited_5fall_2eproto

// ===================================================================

void Example1_EmbeddedMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Example1_EmbeddedMessage::kInt32ValFieldNumber;
const int Example1_EmbeddedMessage::kStringValFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Example1_EmbeddedMessage::Example1_EmbeddedMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_single_5flength_5fdelimited_5fall_2eproto::scc_info_Example1_EmbeddedMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Example1.EmbeddedMessage)
}
Example1_EmbeddedMessage::Example1_EmbeddedMessage(const Example1_EmbeddedMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  stringval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stringval().size() > 0) {
    stringval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringval_);
  }
  int32val_ = from.int32val_;
  // @@protoc_insertion_point(copy_constructor:Example1.EmbeddedMessage)
}

void Example1_EmbeddedMessage::SharedCtor() {
  stringval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  int32val_ = 0;
}

Example1_EmbeddedMessage::~Example1_EmbeddedMessage() {
  // @@protoc_insertion_point(destructor:Example1.EmbeddedMessage)
  SharedDtor();
}

void Example1_EmbeddedMessage::SharedDtor() {
  stringval_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Example1_EmbeddedMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Example1_EmbeddedMessage::descriptor() {
  ::protobuf_single_5flength_5fdelimited_5fall_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_single_5flength_5fdelimited_5fall_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Example1_EmbeddedMessage& Example1_EmbeddedMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_single_5flength_5fdelimited_5fall_2eproto::scc_info_Example1_EmbeddedMessage.base);
  return *internal_default_instance();
}


void Example1_EmbeddedMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Example1.EmbeddedMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  stringval_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  int32val_ = 0;
  _internal_metadata_.Clear();
}

bool Example1_EmbeddedMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Example1.EmbeddedMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    // 判断它的 tag number 值
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 int32Val = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &int32val_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string stringVal = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringval()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stringval().data(), static_cast<int>(this->stringval().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Example1.EmbeddedMessage.stringVal"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Example1.EmbeddedMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Example1.EmbeddedMessage)
  return false;
#undef DO_
}

void Example1_EmbeddedMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Example1.EmbeddedMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 int32Val = 1;
  if (this->int32val() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->int32val(), output);
  }

  // string stringVal = 2;
  if (this->stringval().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringval().data(), static_cast<int>(this->stringval().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Example1.EmbeddedMessage.stringVal");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->stringval(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Example1.EmbeddedMessage)
}

::google::protobuf::uint8* Example1_EmbeddedMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Example1.EmbeddedMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 int32Val = 1;
  if (this->int32val() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->int32val(), target);
  }

  // string stringVal = 2;
  if (this->stringval().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringval().data(), static_cast<int>(this->stringval().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Example1.EmbeddedMessage.stringVal");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->stringval(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Example1.EmbeddedMessage)
  return target;
}

size_t Example1_EmbeddedMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Example1.EmbeddedMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }

  // string stringVal = 2;
  if (this->stringval().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stringval());
  }

  // int32 int32Val = 1;
  if (this->int32val() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->int32val());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Example1_EmbeddedMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Example1.EmbeddedMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const Example1_EmbeddedMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Example1_EmbeddedMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Example1.EmbeddedMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Example1.EmbeddedMessage)
    MergeFrom(*source);
  }
}

void Example1_EmbeddedMessage::MergeFrom(const Example1_EmbeddedMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Example1.EmbeddedMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.stringval().size() > 0) {

    stringval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringval_);
  }
  if (from.int32val() != 0) {
    set_int32val(from.int32val());
  }
}

void Example1_EmbeddedMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Example1.EmbeddedMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Example1_EmbeddedMessage::CopyFrom(const Example1_EmbeddedMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Example1.EmbeddedMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Example1_EmbeddedMessage::IsInitialized() const {
  return true;
}

void Example1_EmbeddedMessage::Swap(Example1_EmbeddedMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Example1_EmbeddedMessage::InternalSwap(Example1_EmbeddedMessage* other) {
  using std::swap;
  stringval_.Swap(&other->stringval_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(int32val_, other->int32val_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Example1_EmbeddedMessage::GetMetadata() const {
  protobuf_single_5flength_5fdelimited_5fall_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_single_5flength_5fdelimited_5fall_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Example1::InitAsDefaultInstance() {
  ::_Example1_default_instance_._instance.get_mutable()->embeddedexample1_ = const_cast< ::Example1_EmbeddedMessage*>(
      ::Example1_EmbeddedMessage::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Example1::kStringValFieldNumber;
const int Example1::kBytesValFieldNumber;
const int Example1::kEmbeddedExample1FieldNumber;
const int Example1::kRepeatedInt32ValFieldNumber;
const int Example1::kRepeatedStringValFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Example1::Example1()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_single_5flength_5fdelimited_5fall_2eproto::scc_info_Example1.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Example1)
}
Example1::Example1(const Example1& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      repeatedint32val_(from.repeatedint32val_),
      repeatedstringval_(from.repeatedstringval_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  stringval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stringval().size() > 0) {
    stringval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringval_);
  }
  bytesval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bytesval().size() > 0) {
    bytesval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytesval_);
  }
  if (from.has_embeddedexample1()) {
    embeddedexample1_ = new ::Example1_EmbeddedMessage(*from.embeddedexample1_);
  } else {
    embeddedexample1_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:Example1)
}

void Example1::SharedCtor() {
  stringval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bytesval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  embeddedexample1_ = NULL;
}

Example1::~Example1() {
  // @@protoc_insertion_point(destructor:Example1)
  SharedDtor();
}

void Example1::SharedDtor() {
  stringval_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bytesval_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete embeddedexample1_;
}

void Example1::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Example1::descriptor() {
  ::protobuf_single_5flength_5fdelimited_5fall_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_single_5flength_5fdelimited_5fall_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Example1& Example1::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_single_5flength_5fdelimited_5fall_2eproto::scc_info_Example1.base);
  return *internal_default_instance();
}


void Example1::Clear() {
// @@protoc_insertion_point(message_clear_start:Example1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  repeatedint32val_.Clear();
  repeatedstringval_.Clear();
  stringval_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bytesval_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && embeddedexample1_ != NULL) {
    delete embeddedexample1_;
  }
  embeddedexample1_ = NULL;
  _internal_metadata_.Clear();
}

bool Example1::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Example1)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    // get tag number : GetTagFieldNumber(tag) -> static_cast<int>(tag >> kTagTypeBits);
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string stringVal = 1;
      case 1: {
        // tag 是否为 10u
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) { // 10 -> 00001010 -> string
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringval()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stringval().data(), static_cast<int>(this->stringval().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Example1.stringVal"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes bytesVal = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) { // 18 - > 00010010 -> bytes
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bytesval()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Example1.EmbeddedMessage embeddedExample1 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_embeddedexample1()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 repeatedInt32Val = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_repeatedint32val())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 34u, input, this->mutable_repeatedint32val())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string repeatedStringVal = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_repeatedstringval()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->repeatedstringval(this->repeatedstringval_size() - 1).data(),
            static_cast<int>(this->repeatedstringval(this->repeatedstringval_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Example1.repeatedStringVal"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Example1)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Example1)
  return false;
#undef DO_
}

void Example1::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Example1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string stringVal = 1;
  if (this->stringval().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringval().data(), static_cast<int>(this->stringval().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Example1.stringVal");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->stringval(), output);
  }

  // bytes bytesVal = 2;
  if (this->bytesval().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->bytesval(), output);
  }

  // .Example1.EmbeddedMessage embeddedExample1 = 3;
  if (this->has_embeddedexample1()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_embeddedexample1(), output);
  }

  // repeated int32 repeatedInt32Val = 4;
  if (this->repeatedint32val_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _repeatedint32val_cached_byte_size_));
  }
  for (int i = 0, n = this->repeatedint32val_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->repeatedint32val(i), output);
  }

  // repeated string repeatedStringVal = 5;
  for (int i = 0, n = this->repeatedstringval_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->repeatedstringval(i).data(), static_cast<int>(this->repeatedstringval(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Example1.repeatedStringVal");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->repeatedstringval(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Example1)
}

::google::protobuf::uint8* Example1::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Example1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string stringVal = 1;
  if (this->stringval().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringval().data(), static_cast<int>(this->stringval().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Example1.stringVal");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->stringval(), target);
  }

  // bytes bytesVal = 2;
  if (this->bytesval().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->bytesval(), target);
  }

  // .Example1.EmbeddedMessage embeddedExample1 = 3;
  if (this->has_embeddedexample1()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_embeddedexample1(), deterministic, target);
  }

  // repeated int32 repeatedInt32Val = 4;
  if (this->repeatedint32val_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _repeatedint32val_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->repeatedint32val_, target);
  }

  // repeated string repeatedStringVal = 5;
  for (int i = 0, n = this->repeatedstringval_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->repeatedstringval(i).data(), static_cast<int>(this->repeatedstringval(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Example1.repeatedStringVal");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->repeatedstringval(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Example1)
  return target;
}

size_t Example1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Example1)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 repeatedInt32Val = 4;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->repeatedint32val_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _repeatedint32val_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated string repeatedStringVal = 5;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->repeatedstringval_size());
  for (int i = 0, n = this->repeatedstringval_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->repeatedstringval(i));
  }

  // string stringVal = 1;
  if (this->stringval().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stringval());
  }

  // bytes bytesVal = 2;
  if (this->bytesval().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->bytesval());
  }

  // .Example1.EmbeddedMessage embeddedExample1 = 3;
  if (this->has_embeddedexample1()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *embeddedexample1_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Example1::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Example1)
  GOOGLE_DCHECK_NE(&from, this);
  const Example1* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Example1>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Example1)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Example1)
    MergeFrom(*source);
  }
}

void Example1::MergeFrom(const Example1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Example1)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  repeatedint32val_.MergeFrom(from.repeatedint32val_);
  repeatedstringval_.MergeFrom(from.repeatedstringval_);
  if (from.stringval().size() > 0) {

    stringval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringval_);
  }
  if (from.bytesval().size() > 0) {

    bytesval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytesval_);
  }
  if (from.has_embeddedexample1()) {
    mutable_embeddedexample1()->::Example1_EmbeddedMessage::MergeFrom(from.embeddedexample1());
  }
}

void Example1::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Example1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Example1::CopyFrom(const Example1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Example1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Example1::IsInitialized() const {
  return true;
}

void Example1::Swap(Example1* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Example1::InternalSwap(Example1* other) {
  using std::swap;
  repeatedint32val_.InternalSwap(&other->repeatedint32val_);
  repeatedstringval_.InternalSwap(CastToBase(&other->repeatedstringval_));
  stringval_.Swap(&other->stringval_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  bytesval_.Swap(&other->bytesval_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(embeddedexample1_, other->embeddedexample1_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Example1::GetMetadata() const {
  protobuf_single_5flength_5fdelimited_5fall_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_single_5flength_5fdelimited_5fall_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Example1_EmbeddedMessage* Arena::CreateMaybeMessage< ::Example1_EmbeddedMessage >(Arena* arena) {
  return Arena::CreateInternal< ::Example1_EmbeddedMessage >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Example1* Arena::CreateMaybeMessage< ::Example1 >(Arena* arena) {
  return Arena::CreateInternal< ::Example1 >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
