// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: single_bytes.proto

#ifndef PROTOBUF_INCLUDED_single_5fbytes_2eproto
#define PROTOBUF_INCLUDED_single_5fbytes_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_single_5fbytes_2eproto 

namespace protobuf_single_5fbytes_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_single_5fbytes_2eproto
class BytesExample1;
class BytesExample1DefaultTypeInternal;
extern BytesExample1DefaultTypeInternal _BytesExample1_default_instance_;
namespace google {
namespace protobuf {
template<> ::BytesExample1* Arena::CreateMaybeMessage<::BytesExample1>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class BytesExample1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BytesExample1) */ {
 public:
  BytesExample1();
  virtual ~BytesExample1();

  BytesExample1(const BytesExample1& from);

  inline BytesExample1& operator=(const BytesExample1& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BytesExample1(BytesExample1&& from) noexcept
    : BytesExample1() {
    *this = ::std::move(from);
  }

  inline BytesExample1& operator=(BytesExample1&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BytesExample1& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BytesExample1* internal_default_instance() {
    return reinterpret_cast<const BytesExample1*>(
               &_BytesExample1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BytesExample1* other);
  friend void swap(BytesExample1& a, BytesExample1& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BytesExample1* New() const final {
    return CreateMaybeMessage<BytesExample1>(NULL);
  }

  BytesExample1* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BytesExample1>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BytesExample1& from);
  void MergeFrom(const BytesExample1& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BytesExample1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes repeatedBytesVal = 1;
  int repeatedbytesval_size() const;
  void clear_repeatedbytesval();
  static const int kRepeatedBytesValFieldNumber = 1;
  const ::std::string& repeatedbytesval(int index) const;
  ::std::string* mutable_repeatedbytesval(int index);
  void set_repeatedbytesval(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_repeatedbytesval(int index, ::std::string&& value);
  #endif
  void set_repeatedbytesval(int index, const char* value);
  void set_repeatedbytesval(int index, const void* value, size_t size);
  ::std::string* add_repeatedbytesval();
  void add_repeatedbytesval(const ::std::string& value);
  #if LANG_CXX11
  void add_repeatedbytesval(::std::string&& value);
  #endif
  void add_repeatedbytesval(const char* value);
  void add_repeatedbytesval(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& repeatedbytesval() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_repeatedbytesval();

  // @@protoc_insertion_point(class_scope:BytesExample1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> repeatedbytesval_;
  friend struct ::protobuf_single_5fbytes_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BytesExample1

// repeated bytes repeatedBytesVal = 1;
inline int BytesExample1::repeatedbytesval_size() const {
  return repeatedbytesval_.size();
}
inline void BytesExample1::clear_repeatedbytesval() {
  repeatedbytesval_.Clear();
}
inline const ::std::string& BytesExample1::repeatedbytesval(int index) const {
  // @@protoc_insertion_point(field_get:BytesExample1.repeatedBytesVal)
  return repeatedbytesval_.Get(index);
}
inline ::std::string* BytesExample1::mutable_repeatedbytesval(int index) {
  // @@protoc_insertion_point(field_mutable:BytesExample1.repeatedBytesVal)
  return repeatedbytesval_.Mutable(index);
}
inline void BytesExample1::set_repeatedbytesval(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:BytesExample1.repeatedBytesVal)
  repeatedbytesval_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void BytesExample1::set_repeatedbytesval(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:BytesExample1.repeatedBytesVal)
  repeatedbytesval_.Mutable(index)->assign(std::move(value));
}
#endif
inline void BytesExample1::set_repeatedbytesval(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  repeatedbytesval_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:BytesExample1.repeatedBytesVal)
}
inline void BytesExample1::set_repeatedbytesval(int index, const void* value, size_t size) {
  repeatedbytesval_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:BytesExample1.repeatedBytesVal)
}
inline ::std::string* BytesExample1::add_repeatedbytesval() {
  // @@protoc_insertion_point(field_add_mutable:BytesExample1.repeatedBytesVal)
  return repeatedbytesval_.Add();
}
inline void BytesExample1::add_repeatedbytesval(const ::std::string& value) {
  repeatedbytesval_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:BytesExample1.repeatedBytesVal)
}
#if LANG_CXX11
inline void BytesExample1::add_repeatedbytesval(::std::string&& value) {
  repeatedbytesval_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:BytesExample1.repeatedBytesVal)
}
#endif
inline void BytesExample1::add_repeatedbytesval(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  repeatedbytesval_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:BytesExample1.repeatedBytesVal)
}
inline void BytesExample1::add_repeatedbytesval(const void* value, size_t size) {
  repeatedbytesval_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:BytesExample1.repeatedBytesVal)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
BytesExample1::repeatedbytesval() const {
  // @@protoc_insertion_point(field_list:BytesExample1.repeatedBytesVal)
  return repeatedbytesval_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
BytesExample1::mutable_repeatedbytesval() {
  // @@protoc_insertion_point(field_mutable_list:BytesExample1.repeatedBytesVal)
  return &repeatedbytesval_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_single_5fbytes_2eproto
